### ISSUE TITLE
Update cron to schedule

### ISSUE THREAD

**Issue by eapen** [askedrelic/comcast-bw#3]
[master⚡] heroku addons:add cron:daily
-----> Adding cron:daily to HOSTNAME... done, v8 (free)
       This add-on has been deprecated and will soon be disabled. 
       Please check out the new Scheduler add-on.

**Comment by askedrelic** [comment]
Thanks for pointing this out. When I wrote this, Scheduler was in beta and wasn't really available.

I guess the solution is to migrate my code/docs to using the Scheduler addon now!

**Comment by askedrelic** [comment]
Fixed in fcfc2a7

Instructions are now using the Scheduler addon. Thanks for the notice!
